import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import anthropicRouter from "./anthropic";
import profileRouter from "./profile";
import chatRouter from "./chat";
import journalRouter from "./journal";
import assessmentsRouter from "./assessments";
import practicesRouter from "./practices";
import resourcesRouter from "./resources";
import dashboardRouter from "./dashboard";
import safetyRouter from "./safety";
import notifyRouter from "./notify";
import feedbackRouter from "./feedback";
import storageRouter from "./storage";
import voiceRouter from "./voice";
import careRouter from "./care";
import professionalRouter from "./professional";
import consentRouter from "./consent";
import companionRouter from "./companion";
import appointmentsRouter from "./appointments";
import conciergeRouter from "./concierge";
import imageryRouter from "./imagery";
import bookingRouter from "./booking";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use("/anthropic", anthropicRouter);
router.use(profileRouter);
router.use("/chat", chatRouter);
router.use("/journal", journalRouter);
router.use("/assessments", assessmentsRouter);
router.use("/practices", practicesRouter);
router.use("/resources", resourcesRouter);
router.use("/dashboard", dashboardRouter);
router.use("/safety", safetyRouter);
router.use(notifyRouter);
router.use(feedbackRouter);
router.use(storageRouter);
router.use("/voice", voiceRouter);
router.use("/care", careRouter);
router.use("/professional", professionalRouter);
router.use("/consent", consentRouter);
router.use("/companion", companionRouter);
router.use("/appointments", appointmentsRouter);
router.use("/concierge", conciergeRouter);
router.use("/imagery", imageryRouter);
router.use("/booking", bookingRouter);

export default router;
